version: '3.7'

services:
  server:
    build:
      context: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always
    networks:
      - bridges
    container_name: "backend-fakebook"
  client:
    build:
      context: frontend
    command: npm start
    depends_on:
      - server
      - mysql
    ports:
      - "3000:3000"
    restart: always
    container_name: "frontend-fakebook"
  mysql:
    image: mysql:8.0
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "tigersut"
    ports:
      - "3306:3306"
    networks:
      - bridges
    container_name: "mysql-server"

networks:
  bridges:
